# Refer to the official documentation for information
# on the available options: https://rust-lang.github.io/rustfmt.

max_width = 120
chain_width = 100
use_small_heuristics = "Max"
use_field_init_shorthand = true
use_try_shorthand = true
